version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "8008:8008"
    volumes:
      - ./backend/parsedata:/app/parsedata
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://backend:8008
