version: '3.8'

services:
  backend:
    build:
      context: ./my-backend
    container_name: go-backend
    ports:
      - "8008:8008"
    working_dir: /app
    volumes:
      - ./my-backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./my-frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./my-frontend:/app
      - /app/node_modules
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://localhost:8008
